export const listTab = [
  { name: "all" },
  { name: "nurse" },
  { name: "driver" },
  { name: "developer" },
  { name: "builder" },
  { name: "architect" },
  { name: "engineer" },
  { name: "electrician" },
  { name: "mechanic" },
  { name: "pharmacists" },
  { name: "assistant" },
  { name: "decorator" },
  { name: "designer" },
  { name: "tailor" },
  { name: "seamstress" },
  { name: "teacher" },
  { name: "vendor" },
  { name: "deliverer" },
  { name: "sender" },
  { name: "technician" },
  { name: "mc" },
  { name: "speaker" },
  { name: "conductor" },
  { name: "tutor" },
  { name: "coach" },
  { name: "vet" },
  { name: "doctor" },
  { name: "cleaner" },
  { name: "janitor" },
  { name: "cobbler" },
  { name: "hairdresser" },
  { name: "taxi driver" },
  { name: "officer" },
  { name: "receptionist" },
  { name: "construction worker" },
  { name: "maid" },
  { name: "bodyguard" },
  { name: "supplier" },
  { name: "dress" },
  { name: "carpenter" },
  { name: "event planner" },
  { name: "clinical officer" },
  { name: "hr officer" },
  { name: "cook" },
  { name: "chef" },
  { name: "musician" },
  { name: "producer" },
  { name: "shop keeper" },
  { name: "attendant" },
  { name: "farmer" },
  { name: "salesperson" },
  { name: "roommate" },
  { name: "caretaker" },
  { name: "guard" },
  { name: "truck driver" },
  { name: "manager" },
  { name: "agent" },
  { name: "consultant" },
  { name: "lecturer" },
];
